-- NOTE: This migration was auto-generated by Supabase when the remote schema
-- was pulled back after 20260501030000 was applied manually via the dashboard.
-- It is a safe duplicate: both ADD COLUMN calls are idempotent (IF NOT EXISTS),
-- and cron.schedule with the same job name replaces the existing entry in
-- pg_cron (upsert semantics), so running this again is harmless.

ALTER TABLE public.ai_visibility_settings
  ADD COLUMN IF NOT EXISTS last_scheduled_sync_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Unschedule first so re-running this file never errors on duplicate job names.
DO $$
BEGIN
  PERFORM cron.unschedule('ai-visibility-weekly-sync');
EXCEPTION WHEN OTHERS THEN
  NULL; -- job didn't exist yet, that's fine
END;
$$;

SELECT cron.schedule(
  'ai-visibility-weekly-sync',
  '0 3 * * 1',
  $$
  SELECT net.http_post(
    url    := 'https://qihpywleopgrlvwcffvy.supabase.co/functions/v1/ai-visibility-scheduled-sync',
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body   := '{}'::jsonb
  ) AS request_id;
  $$
);
