-- NOTE: This migration was auto-generated by Supabase when the remote schema
-- was pulled back after 20260501031000 applied the same column via the dashboard.
-- Safe duplicate: IF NOT EXISTS makes this fully idempotent.

ALTER TABLE public.ai_visibility_admin_policy
  ADD COLUMN IF NOT EXISTS weekly_sync_enabled BOOLEAN NOT NULL DEFAULT true;
